language: rust
sudo: false
cache: cargo
rust:
  - 1.20.0
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
env:
  - ARCH=x86_64
  - FEATURES=""
matrix:
  include:
    - rust: stable
      env:
        - ARCH=i686
    - rust: stable
      env:
        - ARCH=i686
        - FEATURES="--features runtime-dispatch-simd"
    - rust: stable
      env:
        - ARCH=x86_64
        - FEATURES="--features runtime-dispatch-simd"
    - rust: beta
      env:
        - ARCH=i686
    - rust: nightly
      env:
        - ARCH=i686
    - rust: nightly
      env:
        - ARCH=x86_64
        - FEATURES="--features generic-simd"
    - rust: nightly
      env:
        - ARCH=x86_64
        - FEATURES="--features generic-simd,runtime-dispatch-simd"
addons:
  apt:
    packages:
      - gcc-multilib
script: |
  echo ARCH=$ARCH
  echo FEATURES=$FEATURES
  echo RUSTFLAGS=$RUSTFLAGS
  curl -sSL https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/test | bash
  cargo test --release $FEATURES && COUNTS="0,10,1000,100000,10000000" cargo bench $FEATURES
