on: 
  push:
    branches:
      - main
  pull_request:

name: Continuous integration

jobs:
  test:
    name: Test suite
    strategy:
      matrix:
        rust:
          - 1.32.0
          - stable
          - beta
          - nightly
        os:
          - macos-latest
          - ubuntu-latest
        arch:
          - i686
          - x86_64
    env:
      ARCH: ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v1
      - name: Install cargo-binstall
        run: |
          curl --location --remote-name https://github.com/ryankurte/cargo-binstall/releases/download/v0.11.1/cargo-binstall-x86_64-unknown-linux-musl.tgz
          tar -zxvf cargo-binstall-x86_64-unknown-linux-musl.tgz
          mv cargo-binstall ~/.cargo/bin
          ls -l ~/.cargo/bin
      - name: Install "build all features"
        uses: actions-rs/cargo@v1.0.3
        with:
          command: binstall
          args: cargo-all-features --no-confirm --version 1.7.0
      - name: Build all features
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build-all-features
      - name: Test all features
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test-all-features
        env:
          RUST_LOG: debug
      - name: bench
        uses: actions-rs/cargo@v1.0.3
        with:
          command: bench
        env:
          RUST_LOG: debug
          COUNTS: 0,10,1000,100000,10000000