on: 
  push:
    branches:
      - main
  pull_request:

name: Continuous integration

jobs:
  test:
    name: Test suite
    strategy:
      matrix:
        rust:
          - 1.32.0
          - stable
          - beta
          - nightly
        os:
          - macos-latest
          - ubuntu-latest
        arch:
          - i686
          - x86_64
        features:
          - default
          - runtime-dispatch-simd
        include:
        - rust: nightly
          features: generic-simd
    env:
      ARCH: ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v1
      - name: Test (default)
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --release
        env:
          RUST_LOG: debug
        if: ${ matrix.features == "default"}
      - name: Test (non-default)
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --release --features ${{ matrix.features }}
        env:
          RUST_LOG: debug
        if: ${ matrix.features != "default"}
      - name: bench
        uses: actions-rs/cargo@v1.0.3
        with:
          command: bench
        env:
          RUST_LOG: debug
          COUNTS: 0,10,1000,100000,10000000